# Generated by Django 5.2.1 on 2025-05-20 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AGElite_store', '0002_productspecification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productspecification',
            name='name',
        ),
    ]
